[package]
name = "CapybaraScan"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"

# WIF
secp256k1 = "0.24"
hex = "0.4"
sha2 = "0.10"
base58 = "0.2"
digest = "0.9"